services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/storedb?allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=mysql
    depends_on:
      mysqldb:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: storedb
      MYSQL_ROOT_PASSWORD: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysqldb", "-u", "root", "-pmysql" ]
      interval: 10s
      timeout: 30s
      retries: 5

networks:
  springapimysql-net: